-- ===========================================================================
-- Indica - dados de exemplo (gerado por npm run seed a partir de lib/demo.ts)
--
-- NÃO EDITE ESTE ARQUIVO À MÃO. Edite lib/demo.ts e rode npm run seed.
--
-- TUDO AQUI É FICTÍCIO: empresas, pessoas e links inventados. Serve para ver
-- o produto cheio antes de a coleta real chegar nos ~25-30 itens que o doc
-- exige para lançar. Apague antes de abrir para o público:
--
--   delete from public.oportunidades where destino like '%exemplo.invalid%'
--      or destino like '%mail.invalid%' or destino like '@%.exemplo';
-- ===========================================================================

insert into public.oportunidades
  (titulo, organizacao, tipo, area, formato, localidade, faculdade_alvo, prazo, remuneracao, contexto, modo_candidatura, destino, quem_trouxe, quem_trouxe_faculdade, exibicao_quem_trouxe, publicada_em)
values
  ('Analista de sourcing', 'Vetor Capital', 'vaga', 'VC/PE', 'estagio', 'São Paulo', NULL, current_date + 6, 'R$ 3.200 + bônus', 'Time de 4 pessoas, o sócio entrevista pessoalmente. Processo inteiro em 10 dias: conversa, case curto de mercado, papo final. Querem alguém que já tenha mexido com tese de investimento, nem que seja em júnior de finanças.', 'ponte', 'beatriz.exemplo@mail.invalid', 'Beatriz Andrade', 'Insper', 'primeiro-nome-faculdade', now() - interval '0 days'),
  ('Off-cycle de research', 'Aroeira Asset', 'off-cycle', 'MF', 'estagio', 'São Paulo', NULL, current_date + 3, 'R$ 5.000', 'Seis meses, começa em janeiro. Não abre no site: eles pegam indicação de quem já passou. Prova de Excel e um case de valuation no segundo dia. Quem vai bem costuma virar efetivo.', 'link', 'https://exemplo.invalid/aroeira/off-cycle', 'Rafael Nogueira', NULL, 'nome', now() - interval '1 days'),
  ('Primeiro engenheiro de dados', 'Nuvem Nove', 'vaga', 'dados', 'CLT', 'remoto', NULL, NULL, 'R$ 8.000 a R$ 11.000', 'Seed, 9 pessoas, acabaram de levantar. É o primeiro hire de dados: você define o stack. Fundador é técnico e responde em horas. Aceita quem está no último ano se der para fazer 30h.', 'link', 'https://exemplo.invalid/nuvemnove/dados', 'Camila Rocha', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '1 days'),
  ('Estágio em produto', 'Órbita Labs', 'vaga', 'produto', 'estagio', 'São Paulo (híbrido, 3x)', NULL, current_date + 12, 'R$ 3.000', 'Vaga que abriu porque a pessoa saiu para o mestrado. Time de produto tem 3 pessoas, você pega uma squad inteira em dois meses. Eles valorizam quem já tocou projeto de entidade estudantil de verdade.', 'ponte', '@joaovitor.exemplo', 'João Vitor Salles', 'ITA', 'primeiro-nome-faculdade', now() - interval '2 days'),
  ('Backend Go (pleno)', 'Malha Logística', 'vaga', 'tech/dev', 'PJ', 'remoto', NULL, NULL, 'R$ 12.000 PJ', 'Scale-up série B. A vaga não está no site nem no LinkedIn: estão contratando só por indicação para fugir do volume. Teste técnico é take-home de 4h, sem pegadinha.', 'ponte', 'https://exemplo.invalid/contato/malha', 'Lucas Ferraz', NULL, 'nome', now() - interval '2 days'),
  ('Analista de M&A', 'Praia Grande Partners', 'off-cycle', 'MF', 'estagio', 'São Paulo', 'Insper', current_date + 9, 'R$ 4.500', 'Boutique de 12 pessoas. Abriram essa turma só para o Insper esse ano — ano passado foi FGV. Rotina puxada, mas o deal flow é real e você assina o material.', 'link', 'https://exemplo.invalid/pgp/analista', 'Marina Duarte', NULL, 'anonimo', now() - interval '3 days'),
  ('Estágio em growth', 'Cardume', 'vaga', 'produto', 'estagio', 'remoto', NULL, NULL, 'R$ 2.800', 'Fintech seed. Fundadora contrata rápido: se você mandar até quarta, conversa na sexta. Quer alguém que saiba escrever bem — metade do trabalho é copy de aquisição.', 'link', 'https://exemplo.invalid/cardume/growth', 'Pedro Antunes', 'USP', 'primeiro-nome-faculdade', now() - interval '3 days'),
  ('Cientista de dados júnior', 'Instituto Barlavento', 'vaga', 'dados', 'CLT', 'Rio de Janeiro', NULL, current_date + 20, 'R$ 7.000', 'Terceiro setor, mas paga mercado. Projeto de dados públicos de educação. Aceitam recém-formado. Processo tem uma etapa de apresentação para o conselho.', 'link', 'https://exemplo.invalid/barlavento/dados', 'Helena Prado', NULL, 'nome', now() - interval '4 days'),
  ('Sourcing analyst', 'Talos Ventures', 'vaga', 'VC/PE', 'estagio', 'São Paulo', NULL, current_date + 5, 'R$ 3.500', 'Fundo early-stage. Você vai passar o dia falando com fundador, não montando planilha. Eles preferem quem já empreendeu ou trabalhou em startup pequena a quem tem estágio em banco.', 'ponte', 'beatriz.exemplo@mail.invalid', 'Beatriz Andrade', 'Insper', 'primeiro-nome-faculdade', now() - interval '4 days'),
  ('Engenheiro de software (novo time)', 'Farol Saúde', 'vaga', 'tech/dev', 'CLT', 'São Paulo (híbrido)', NULL, NULL, 'R$ 9.500', 'Estão montando um time novo do zero — 4 vagas, mesma senioridade. Quem entra agora pega escopo de tech lead em um ano. Stack: TypeScript, Postgres, AWS.', 'link', 'https://exemplo.invalid/farol/eng', 'Gustavo Lins', 'ITA', 'primeiro-nome-faculdade', now() - interval '5 days'),
  ('Off-cycle em equity research', 'Serra Azul Investimentos', 'off-cycle', 'MF', 'estagio', 'São Paulo', NULL, current_date + 2, 'R$ 4.800', 'Cobertura de varejo e consumo. O analista sênior é quem decide e ele lê todos os e-mails. Mandar uma tese de uma página junto com o currículo funciona muito melhor que só o CV.', 'contato', 'recrutamento.exemplo@mail.invalid', 'Rafael Nogueira', NULL, 'nome', now() - interval '5 days'),
  ('Estágio em consultoria de dados', 'Meridiano Consultoria', 'vaga', 'consultoria', 'estagio', 'São Paulo', NULL, current_date + 15, 'R$ 3.000', 'Butique de 20 pessoas, clientes de indústria. Não faz case de MBB: o processo é uma conversa técnica e um exercício de SQL.', 'link', 'https://exemplo.invalid/meridiano/estagio', 'Ana Carolina Melo', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '6 days'),
  ('Primeiro hire de operações', 'Semente Agro', 'vaga', 'outros', 'CLT', 'Campinas', NULL, NULL, 'R$ 6.000 + equity', 'Agtech pré-seed, 5 pessoas. Tem equity na mesa para o primeiro de ops. Fundador veio de fazenda e de engenharia — quer alguém que não tenha medo de ir a campo.', 'ponte', '@camila.exemplo', 'Camila Rocha', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '6 days'),
  ('Estágio em engenharia de plataforma', 'Quadrante Tech', 'vaga', 'tech/dev', 'estagio', 'remoto', 'ITA', current_date + 10, 'R$ 4.000', 'Abriram duas vagas exclusivas para o ITA porque os dois últimos estagiários vieram de lá e deram muito certo. Kubernetes e Go, com mentoria de verdade.', 'link', 'https://exemplo.invalid/quadrante/estagio', 'Gustavo Lins', 'ITA', 'primeiro-nome-faculdade', now() - interval '7 days'),
  ('Analista de investimentos', 'Fundo Cambuci', 'vaga', 'VC/PE', 'CLT', 'São Paulo', NULL, current_date + 25, 'R$ 9.000', 'Growth equity, cheques de R$ 20M a R$ 60M. Contratam um por ano e sempre por indicação. Modelagem pesada — se você não gosta de planilha, não é aqui.', 'contato', 'https://exemplo.invalid/cambuci/contato', 'Marina Duarte', NULL, 'anonimo', now() - interval '8 days'),
  ('Product analyst', 'Trilho', 'vaga', 'dados', 'CLT', 'remoto', NULL, NULL, 'R$ 7.500', 'Marketplace série A. A vaga é metade produto, metade dados. Head de produto responde em um dia e dá feedback detalhado mesmo para quem não passa.', 'link', 'https://exemplo.invalid/trilho/analyst', 'Pedro Antunes', 'USP', 'primeiro-nome-faculdade', now() - interval '9 days'),
  ('Off-cycle em crédito', 'Ipê Capital', 'off-cycle', 'MF', 'estagio', 'São Paulo', NULL, current_date + 18, 'R$ 5.200', 'Crédito estruturado. Turma de dois. Eles avisam que a primeira semana é pesada de propósito, para ver quem aguenta. Quem fica costuma receber oferta.', 'link', 'https://exemplo.invalid/ipe/offcycle', 'Helena Prado', NULL, 'nome', now() - interval '10 days'),
  ('Estágio em design de produto', 'Cardume', 'vaga', 'produto', 'estagio', 'remoto', NULL, NULL, 'R$ 2.800', 'Mesma fintech do growth. Aqui querem portfólio, não currículo — dois projetos bem explicados bastam.', 'link', 'https://exemplo.invalid/cardume/design', 'Ana Carolina Melo', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '11 days'),
  ('Engenheiro de machine learning', 'Vespa AI', 'vaga', 'tech/dev', 'PJ', 'remoto', NULL, current_date + 30, 'R$ 14.000 PJ', 'Time de 6, todos sêniores, e é o primeiro júnior que eles contratam. Aceitam mestrando. Pedem para você mandar um repositório junto — leem de verdade.', 'ponte', 'lucas.exemplo@mail.invalid', 'Lucas Ferraz', NULL, 'nome', now() - interval '12 days'),
  ('Analista de operações', 'Boto Logística', 'vaga', 'outros', 'CLT', 'Manaus', NULL, NULL, 'R$ 5.500', 'Operação de última milha na Amazônia. Vaga difícil de preencher porque quase ninguém procura por isso — e é justamente por isso que quem entra cresce rápido.', 'link', 'https://exemplo.invalid/boto/ops', 'João Vitor Salles', 'ITA', 'primeiro-nome-faculdade', now() - interval '13 days'),
  ('Estágio em VC (plataforma)', 'Talos Ventures', 'vaga', 'VC/PE', 'estagio', 'São Paulo', 'USP', current_date + 14, 'R$ 3.500', 'Time de plataforma ajuda as investidas a contratar. Abriram para a USP porque a última pessoa veio da Poli. Você fala com fundador todo dia.', 'ponte', '@pedro.exemplo', 'Pedro Antunes', 'USP', 'primeiro-nome-faculdade', now() - interval '14 days'),
  ('Desenvolvedor front-end', 'Sinal Verde', 'vaga', 'tech/dev', 'CLT', 'Belo Horizonte (híbrido)', NULL, NULL, 'R$ 8.000', 'Healthtech série A. O CTO contrata pessoalmente e o processo tem uma etapa de pair programming — quem gosta de conversar código se dá muito bem.', 'link', 'https://exemplo.invalid/sinalverde/front', 'Gustavo Lins', 'ITA', 'primeiro-nome-faculdade', now() - interval '15 days'),
  ('Off-cycle em private equity', 'Monte Verde Partners', 'off-cycle', 'MF', 'estagio', 'São Paulo', NULL, current_date + 22, 'R$ 6.000', 'Seis meses. Fundo médio, tese de saúde e educação. Contratam dois por semestre e sempre pegam quem já fez off-cycle antes — mas abriram uma vaga para quem nunca fez.', 'contato', 'vagas.exemplo@mail.invalid', 'Rafael Nogueira', NULL, 'nome', now() - interval '16 days'),
  ('Analista de BI', 'Rede Andorinha', 'vaga', 'dados', 'CLT', 'remoto', NULL, NULL, 'R$ 6.500', 'Varejo, 200 lojas. O trabalho é de verdade: a diretoria toma decisão com o dashboard que você faz. Ferramenta é Looker e dbt.', 'link', 'https://exemplo.invalid/andorinha/bi', 'Helena Prado', NULL, 'nome', now() - interval '17 days'),
  ('Estágio em estratégia', 'Grupo Caravela', 'vaga', 'consultoria', 'estagio', 'São Paulo', NULL, current_date + 28, 'R$ 3.200', 'Área de estratégia interna de um grupo familiar grande. Trabalha direto com o board. Não tem processo estruturado: mandam o CV para o diretor e ele chama.', 'ponte', 'marina.exemplo@mail.invalid', 'Marina Duarte', NULL, 'anonimo', now() - interval '18 days'),
  ('Engenheiro de dados (primeiro do time)', 'Pauta Mídia', 'vaga', 'dados', 'PJ', 'remoto', NULL, NULL, 'R$ 10.000 PJ', 'Startup de mídia, 15 pessoas. Hoje tudo roda em planilha; você monta a base do zero. Liberdade total de stack, com a contrapartida de não ter ninguém para perguntar.', 'link', 'https://exemplo.invalid/pauta/dados', 'Camila Rocha', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '19 days'),
  ('Analista de produto', 'Órbita Labs', 'vaga', 'produto', 'CLT', 'São Paulo (híbrido, 3x)', NULL, current_date + 35, 'R$ 7.000', 'Segunda vaga do mesmo time de produto. Essa é para quem já formou. Eles contratam devagar e avisam: o processo leva umas três semanas.', 'link', 'https://exemplo.invalid/orbita/analista', 'João Vitor Salles', 'ITA', 'primeiro-nome-faculdade', now() - interval '21 days'),
  ('Off-cycle em macro', 'Serra Azul Investimentos', 'off-cycle', 'MF', 'estagio', 'São Paulo', 'Unicamp', current_date + 40, 'R$ 5.000', 'Mesa de macro. Abriram para o Instituto de Economia da Unicamp esse ano. Pedem econometria de verdade — quem só fez a cadeira básica sofre.', 'link', 'https://exemplo.invalid/serraazul/macro', 'Ana Carolina Melo', 'Unicamp', 'primeiro-nome-faculdade', now() - interval '24 days');
